{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hello-world-argo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "hello-world-argo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManagerIssuer }}
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.ingress.entrypoints }}
    traefik.ingress.kubernetes.io/router.tls: "{{ .Values.ingress.tls }}"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "hello-world-argo.fullname" . }}
            port:
              number: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}