apiVersion: v1
kind: Service
metadata:
  name: { { include "hello-world-argo.fullname" . } }
  labels:
    app.kubernetes.io/name: { { include "hello-world-argo.name" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
    app.kubernetes.io/component: app
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: { { include "hello-world-argo.name" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
