# Default values for hello-world-argo
replicaCount: 1

image:
  repository: ghcr.io/juninmd/hello-world-argo
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  host: hello-world-argo.example.com
  certManagerIssuer: letsencrypt-http01
  entrypoints: web,websecure
  tls: "true"
  tlsSecretName: hello-world-argo-tls-cert

# Cronjob configuration
cronjob:
  # Cron expression - every 5 minutes by default
  schedule: "*/5 * * * *"
  # Webhook URL
  webhookUrl: "https://webhook.site/43cbe200-bddc-450a-bece-bb0905ad3ca4"
  # Timezone
  timezone: "America/Sao_Paulo"
  # Job history limits
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  # Restart policy
  restartPolicy: OnFailure
  # Backoff limit for failed jobs
  backoffLimit: 3

serviceAccount:
  create: true
  name: ""

podSecurityContext:
  fsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
