name: Build and Deploy with ArgoCD

on:
  push:
    branches: [main, master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Helm values with new image
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          IMAGE_TAG="${BRANCH_NAME}-${GITHUB_SHA:0:7}"

          # Update the tag in values.yaml
          sed -i "s|tag: \".*\"|tag: \"$IMAGE_TAG\"|g" helm/values.yaml

          # Commit the changes back to trigger ArgoCD sync
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add helm/values.yaml
          git diff --staged --quiet || git commit -m "Update image tag to $IMAGE_TAG [skip ci]"
          git push

      - name: Validate Deployment
        run: |
          echo "✅ Image built and pushed successfully!"
          echo "✅ Helm values updated and committed!"
          echo "ArgoCD will automatically sync the application."
